workflows:
    native-android:
        name: Native Android
        instance_type: mac_pro

        environment:
            vars:
                # Android Keystore environment variables
                CM_KEYSTORE: Encrypted(...) # <-- Put your encrypted keystore file here
                CM_KEYSTORE_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore password here
                CM_KEY_ALIAS_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore alias password here
                CM_KEY_ALIAS_USERNAME: Encrypted(...) # <-- Put your encrypted keystore alias username here     
            node: latest
            xcode: 12.2
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop
                  include: true
                  source: true
        scripts:
            - name: Set Android SDK location
              script:
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
            - name: Set up keystore
              script: |
                    echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
                    cat >> "$FCI_BUILD_DIR/key.properties" <<EOF
                    storePassword=$CM_KEYSTORE_PASSWORD
                    keyPassword=$CM_KEY_ALIAS_PASSWORD
                    keyAlias=$CM_KEY_ALIAS_USERNAME
                    storeFile=/tmp/keystore.jks
                    EOF
            - name: Build Android debug APK
              script: |
                ./gradlew assembleDebug
            - name: Build Android test APK
              script: |
                ./gradlew assembleAndroidTest
            - name: Build Android production release
              script: |
                ./gradlew assembleRelease    
        artifacts:
            - app/build/outputs/**/*.apk
        publishing:
            email:
                recipients:
                    - kalgi@nevercode.io
                notify:
                  success: true
                  failure: false   
           
